### ISSUE TITLE
Make sure that at most one CSS resource is loaded per artifact 

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar-loader#11]
The current way to load CSS is already pretty neat. :+1:

However, the style loader will embed multiple CSS files for artifacts that have both CSS for the default theme and for the application theme.

Also, if we extract styles into a release bundle, that bundle will embed multiple CSS sources in the same cases, increasing download size and possibly creating conflicts.

The `laxar-loader` needs to ensure that only one style source is used per artifact. It should not try to embed a `default.theme` stylesheet if a themed stylesheet is available.

Also, we should probably (at least) warn, if multiple themes are requested when loading an artifacts bundle.

**Comment by jpommerening** [comment]
Implemented on `master` (`v0.5.0`)

**Comment by jpommerening** [comment]
Implemented on `master` (`v0.5.0`) via #16
