### ISSUE TITLE
remove special handling for themes (was: handle webpack resolve.root)

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar-loader#18]
When resolving artifacts ourselves (using their container directory), not only aliases but also the configured resolve-roots should be taken into account.

For example, LaxarJS UiKit (containing the default theme) may be living under `bower_components` without having a specific alias configured. If `bower_components` is configured as a resolve-root, the laxar-loader should be able to find the default theme.

**Comment by jpommerening** [comment]
Hmm … so in [`resolve`](https://github.com/LaxarJS/laxar-loader/blob/8c456187dfac2aaa325eccaaf29da57197f7ba23/src/index.js#L180) and `resolveAliases` we would try each entry of `resolve.modules` in addition to `context`. Asynchronously, of course.

The main issue leading to the addition of the manual alias expansion was the necessity to resolve directories, theme directories in particular, while webpack can only resolve things it has a loader for (files, typically). I think we could make `theme.json` files mandatory, drop a bunch of code here and in `laxar-tooling`, and be done with it. Sure, those small things add up to a non-trivial migration plan but we gain a system that is less complex in return.

@x1B, @alex3683:
- [ ] make `theme.json` files mandatory, remove code

**Comment by x1B** [comment]
I agree. Using theme.json files has many advantages (again, the theme-name vs. package-name comes into mind).

**Comment by jpommerening** [comment]
Oh, turns out we're having the same problem with layouts.
Mandating `layout.json` files as well seems like a reasonable tradeoff, even if it's a little bit more boilerplate.

**Comment by jpommerening** [comment]
Implemented on `master` (`v2.0.0-alpha.3`)

### BREAKING CHANGE

As mentioned in LaxarJS/laxar-tooling#27 and LaxarJS/laxar-tooling#28, descriptor files for themes and layouts are now mandatory. This means, every theme and layout needs to have `theme.json`/`layout.json` file.
