### ISSUE TITLE
using singular entry with multiple values should work or warn

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar-loader#19]
Currently, passing multiple values to a singular option can have weird effects (e.g. LaxarJS will be looking for a theme called `cube,default.theme` if `theme[]=cube` is used).

For simplicity, we might simply treat the singular options in the same way as the plural options.

**Comment by jpommerening** [comment]
Implemented on `master` (`v2.0.0`)

*Note:* any combination of `flow`, `flow[]`, `flows` and `flows[]` is now allowed.
