### ISSUE TITLE
ensure webpack 2 compatibility

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar-loader#22]
Webpack 2 is about to be released for real. We should move directly to it for LaxarJS v2, to avoid projects having to make the switch afterwards.

**Comment by x1B** [comment]
https://github.com/webpack/webpack/issues/3195

**Comment by jpommerening** [comment]
The test-harness to run webpack on a mocked filesystem is a bit weird. I pushed a patch that makes sure the tests work with webpack 2. `README.md` still uses webpack 1 format though.

**Comment by x1B** [comment]
:+1: thanks for the heads-up

**Comment by x1B** [comment]
Before merging this, we should probably wait for the 2.0.0 final of webpack, so that we won't have to change the package dependency field twice.
