### ISSUE TITLE
Loading artifacts (flows, widgets) broken

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar-loader#29]
It seems that loading artifacts (flow, widget) broke between alpha.3 and rc.0.

We should definitely look into improving the test situation :)

**Comment by x1B** [comment]
@jpommerening could this be due to #19

**Comment by jpommerening** [comment]
@x1B clarify?

**Comment by x1B** [comment]
@jpommerening the sympton of the problem is that the ArtifactProvider fails with an error such as "Artifact main not found in flows"

**Comment by x1B** [comment]
@jpommerening Tomorrow, I'll try to bisect but I can already confirm that v2.0.0-alpha.3 is known to work.

**Comment by jpommerening** [comment]
Could be #18. But what's the deal with this: https://github.com/LaxarJS/laxar-loader/commit/5fae0dda9b0f07cb24e4c9d1bef6030db8c3928a ?

**Comment by x1B** [comment]
@jpommerening we bumped all deps to 2.0.0 in -rc.0 (several of the artifacts, e.g. the generator, were already pointing to that version), so that rc are actually eligible as releases (that's why they're called rc I guess).

When using yarn, you can just let it pick the latest rc for you.
Does it cause problems otherwise?

**Comment by jpommerening** [comment]
Ah, that's good to know because `npm` treats _all_ pre-release versions as "smaller than" the released version. (At least it sorts them alphanumerically.)

**Comment by jpommerening** [comment]
@x1B: Found the issue! Of course it was #19 just like you initially assumed!
Typo, here: [items.**lenth**](https://github.com/LaxarJS/laxar-loader/commit/432077583add77a553717e8d672ae36d8040346f#diff-1fdf421c05c1140f6d71444ea2b27638R185)

Could you take care of that for me? :)

**Comment by x1B** [comment]
![Can do](https://img.memesuper.com/802795d8599684204f032f47f6b0cde8_poster-mr-meeseeks-can-do_220-200.jpeg)

**Comment by x1B** [comment]
Fixed on `master` (`v2.0.0`)

@jpommerening thx for the pointer
