### ISSUE TITLE
Can no longer load project without laxar.config.js

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar-loader#30]
Apparently, the default paths are no longer working.

**Comment by x1B** [comment]
For example, the shop-demo does no longer work with laxar-loader RC1.

`Can't resolve 'main.json'`

As a workaround, a `laxar.config.js` containing the default paths can be added.

However, this does not seem to help when trying to run browser specs:

`Can't resolve './application/widgets/article-browser-widget/widget.json'` (repeated for all widgets).

**Comment by x1B** [comment]
@jpommerening pretty sure all of this still worked with `alpha.3` -- any ideas?

**Comment by x1B** [comment]
Can be reproduced using [the shop-demo@8c8c229](https://github.com/LaxarJS/shop-demo/commit/8c8c229). Neither `npm start` nor `npm test` work using the laxar-loader RC.
When pinning laxar-loader to `v2.0.0-alpha.3`, both seem to work fine.

**Comment by jpommerening** [comment]
I guess this worked because resolveAliases or what its name was also path.resolved relative to options.context

If you look at the error message you will probably find "not found in '…/laxar-loader'". The issue might be that loaderContext.context points to the laxar loader module because that is where the entry-point "artifacts" is located. We should change resolve to use loaderContext.options.context instead.

(I did some head scratching after our last exchange in the other ticket)

**Comment by x1B** [comment]
@jpommerening assigning to you as discussed

**Comment by jpommerening** [comment]
To make matters worse `path.join()` turned `./application/flows` + `main.json` into `application/flows/main.json`, removing the leading `./`. When reading paths from the `laxar.config.js`, we make sure we resolve the paths relative to the file before doing anything else. We don't have a chance to do this when relying on the defaults.
Previously the `resolveAliases` function caught all resolve errors and implicitly did a `path.resolve` with the webpack base directory as a reference. Just fixing `path.join()` is sufficient to fix this problem, but we should change the `resolve()` function as well.

**Comment by x1B** [comment]
@jpommerening would it help to generate the defaults to be absolute right away (using `require.resolve`)? This would not work if the directories are missing, but the defaults do not help in that case, anyway.

**Comment by jpommerening** [comment]
@x1B: How could we do that?

Please check if the (not yet released) change in `laxar-tooling` fixes your problem with the browser specs of your current setup. It works for me™

**Comment by x1B** [comment]
@jpommerening can confirm that these two changes fix the reported issues. Disregard my previous suggestion; I see that`require.resolve` would not look in the right places.

**Comment by x1B** [comment]
_Closing._ @jpommerening thanks for the fix!
